name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.23"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  golangci:
    strategy:
      fail-fast: false
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      timeout-minutes: 10 # fail fast. sometimes this step takes an extremely long time
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Get Path1
      run: |
        echo $GITHUB_PATH
      shell: bash
    - name: Set Path
      run: |
        echo "${{ inputs.working-directory }}/tools/custom-gcl" >> $GITHUB_PATH
      shell: bash
    - name: Get Path2
      run: |
        echo $GITHUB_PATH
      shell: bash
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.63
        args:
        - --no-config
        - --disable-all
        working-directory: ${{ matrix.dir }}