name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.23"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  golangci:
    strategy:
      fail-fast: false
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      timeout-minutes: 10 # fail fast. sometimes this step takes an extremely long time
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Get Path1
      run: |
        echo $GITHUB_PATH
      shell: bash
    - name: Set Path
      run: |
        echo "$(pwd)/tools" >> $GITHUB_PATH
      shell: bash
    - name: Get Path2
      run: |
        echo "$PATH"
      shell: bash
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.63
        args: "--no-config --disable-all"
    - name: Build custom linter
      if: success() || failure()
      run: |
        golangci-lint custom
    - name: Check for linter
      if: success() || failure()
      run: ls -a ./tools
    - name: Check cwd
      if: success() || failure()
      run: ls -a .
    - name: Which linter?
      if: success() || failure()
      run: which golangci-lint
    - name: Run golangci-lint
      if: success() || failure()
      uses: golangci/golangci-lint-action@v6
      with:
        install-mode: 'none'
        args: "-v"